# Generated by Django 4.1.3 on 2022-12-06 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law_office_backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2022, 12, 6)),
        ),
    ]
