# Generated by Django 4.1.3 on 2022-12-06 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('law_office_backend_app', '0003_categories_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='law_office_backend_app.categories'),
        ),
    ]
